_core:
  default_config_hash: 2YZqaocAn-mTIEZ9ScbWdrIR5cFXdxybxp41CWjb7Ss
mode: development
access:
  read_only_mode: false
  config_only_mode: false
  config_only_allowed_write_kinds:
    - config
  allowed_scopes:
    - read
    - write
  default_scopes:
    - read
  trust_scopes_via_header: false
  trust_scopes_via_query: false
  trust_scopes_via_env: true
  audit_logging: true
rate_limits:
  broken_link_scan:
    max_per_hour: 10
    max_urls_per_scan: 500
  content_search:
    max_per_minute: 30
rate_limiting:
  enabled: false
  trust_client_id_header: false
  max_writes_per_minute: 30
  max_writes_per_hour: 500
  max_deletes_per_hour: 50
  max_structure_changes_per_hour: 100
allowed_hosts:
  - localhost
  - '*.local'
output:
  max_items: 100
  include_sensitive: false
webhooks:
  enabled: false
  url: ''
  secret: ''
  allowed_hosts: {  }
  timeout: 5
  batch_notifications: true
  notify_on:
    - create
    - update
    - delete
    - structure
